environment:
  SSL_CERT_FILE: "C:\\OpenSSL\\cacert.pem"
  global:
    PROJECT_NAME: tagaton
  matrix:
      # 1.1.0, 64/32 bit
      - TARGET: i686-pc-windows-gnu
        BITS: 32
        MSYS2: 1
        OPENSSL_VERSION: 1_1_0c
      - TARGET: x86_64-pc-windows-msvc
        BITS: 64
        OPENSSL_VERSION: 1_1_0c
        OPENSSL_DIR: C:\OpenSSL

      # 1.0.2, 64/32 bit
      - TARGET: x86_64-pc-windows-gnu
        BITS: 64
        MSYS2: 1
        OPENSSL_VERSION: 1_0_2j
      - TARGET: i686-pc-windows-msvc
        BITS: 32
        OPENSSL_VERSION: 1_0_2j
        OPENSSL_DIR: C:\OpenSSL
install:
  # install OpenSSL
  - ps: Start-FileDownload "http://slproweb.com/download/Win${env:BITS}OpenSSL-${env:OPENSSL_VERSION}.exe"
  - Win%BITS%OpenSSL-%OPENSSL_VERSION%.exe /SILENT /VERYSILENT /SP- /DIR="C:\OpenSSL"
  - ps: Start-FileDownload "https://curl.haxx.se/ca/cacert.pem" -FileName "C:\OpenSSL\cacert.pem"

  # Rust
  - ps: Start-FileDownload "https://static.rust-lang.org/dist/rust-nightly-${env:TARGET}.exe"
  - rust-nightly-%TARGET%.exe /VERYSILENT /NORESTART /DIR="C:\Program Files (x86)\Rust"
  - SET PATH=%PATH%;C:\Program Files (x86)\Rust\bin
  - if defined MSYS2_BITS set PATH=%PATH%;C:\msys64\mingw%MSYS2_BITS%\bin
  - rustc -V
  - cargo -V

  #SQLite
  - ps: Start-FileDownload 'http://sqlite.org/2016/sqlite-dll-win64-x64-3100200.zip'
  - cmd: 7z e sqlite-dll-win64-x64-3100200.zip -y > nul
  - SET SQLITE3_LIB_DIR=%APPVEYOR_BUILD_FOLDER%

build: false

test_script:
  - git submodule update --init --recursive
  - cargo test --verbose
  - cargo build --release --verbose
  - mkdir staging
  # TODO update this part to copy the artifacts that make sense for your project
  - copy target\release\%PROJECT_NAME%.exe staging
  - cd staging
    # release zipfile will look like 'rust-everywhere-v1.2.3-x86_64-pc-windows-msvc'
  - 7z a ../%PROJECT_NAME%-%APPVEYOR_REPO_TAG_NAME%-%TARGET%.zip *
  - appveyor PushArtifact ../%PROJECT_NAME%-%APPVEYOR_REPO_TAG_NAME%-%TARGET%.zip
  
cache:
- C:\Users\appveyor\.cargo
